remote:
  home: http://localhost:8089

server.port: 8089

#security:
#  oauth2:
#    client:
#      provider:
#        my-keycloak-provider:
#          issuer-uri: http://localhost:8089/realms/miu
#          # Individual properties can also be provided this way
#      #            token-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/token
#      #            authorization-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/auth
#      #            userinfo-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/userinfo
#      #            user-name-attribute: preferred_username
#      registration:
#        keycloak-spring-gateway-client:
#          provider: authentication-service
#          scope: openid
#          client-id: authentication
#          client-secret: abcdefghijkl
#          authorization-grant-type: password
#          redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
